version: '3.7'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      # rpg-content-api:
      #   condition: service_healthy
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/gamedb

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: gamedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gamedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  rpg-content-api:
    build: ./rpg-content-api
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=run.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  content-creator:
    build: ./content-creator
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_APP=run.py
      - OLLAMA_URL=http://ollama.example.com
      - OLLAMA_MODEL=default_model
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
