version: '3.7'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/gamedb

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: gamedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gamedb"]
      interval: 10s
      timeout: 5s
      retries: 5

# Comment out persistent volume temporarily
# volumes:
#  db_data:
