version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      rpg-content-api:
        condition: service_healthy
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/gamedb
      - FLASK_ENV=development

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: gamedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gamedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  rpg-content-api:
    build:
      context: ./rpg-content-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/gamedb
      - FLASK_ENV=development
      - FLASK_APP=run.py
    depends_on:
      content-creator:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  content-creator:
    build:
      context: ./content_creator
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
