version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - db
      - rpg-content-api
      - ai-agents
      - rule-extraction
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gamedb
      - RPG_CONTENT_API_URL=http://rpg-content-api:8000

  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gamedb

  rpg-content-api:
    build: ./rpg-content-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gamedb

  ai-agents:
    build: ./ai-agents
    depends_on:
      - db
      - rpg-content-api

  rule-extraction:
    build: ./rule-extraction
    depends_on:
      - db
      - rpg-content-api
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gamedb

volumes:
  db-data:
