pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials-id')
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository
                checkout scm
            }
        }
        stage('Build and Push Images') {
            steps {
                script {
                    // Log in to Docker Hub
                    sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"

                    // Change to project-root directory
                    dir('project-root') {
                        // Build and push the Docker images using Docker Compose
                        sh 'docker-compose -f docker-compose-build.yml build'
                        sh 'docker-compose -f docker-compose-build.yml push'
                    }

                    // Log out from Docker Hub
                    sh 'docker logout'
                }
            }
        }
        stage('Test') {
            steps {
                // Example: Add your test steps here
                echo 'Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                // Example: Add your deployment steps here
                echo 'Deploying application...'
            }
        }
    }
    // post {
    //     failure {
    //         mail to: 'you@example.com',
    //              subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
    //              body: "Something is wrong with ${env.BUILD_URL}"
    //     }
    // }
}
